### torch对数据的一些基础操作

In [2]:
import torch

In [3]:
x = torch.empty(5, 3)

In [4]:
x

tensor([[1.1210e-44, -0.0000e+00, 0.0000e+00],
        [0.0000e+00, 3.5873e-43, 3.6013e-43],
        [3.5873e-43, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.1614e-41, 0.0000e+00]])

In [7]:
x = torch.rand(5, 3)

In [8]:
x

tensor([[0.6688, 0.8004, 0.2721],
        [0.0961, 0.3156, 0.8877],
        [0.7442, 0.5633, 0.2750],
        [0.3196, 0.1612, 0.0199],
        [0.6833, 0.8109, 0.6096]])

In [17]:
x = x.new_ones(5, 3, dtype=torch.long)

In [19]:
x

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [14]:
x = torch.tensor([5.5, 3])

In [15]:
x

tensor([5.5000, 3.0000])

In [20]:
x.size()

torch.Size([5, 3])

In [32]:
y = torch.rand(5, 3, dtype=torch.double)

In [37]:
y

tensor([[0.1470, 0.0789, 0.2647],
        [0.9601, 0.7546, 0.7900],
        [0.1119, 0.7584, 0.0802],
        [0.0146, 0.2912, 0.8888],
        [0.7785, 0.6150, 0.3576]], dtype=torch.float64)

In [38]:
x = torch.rand_like(y, dtype=torch.double)

In [40]:
x

tensor([[0.1117, 0.5621, 0.5410],
        [0.6749, 0.1983, 0.8946],
        [0.4937, 0.5692, 0.3421],
        [0.7924, 0.5206, 0.1811],
        [0.3576, 0.7579, 0.6857]], dtype=torch.float64)

In [39]:
torch.add(x, y)

tensor([[0.2587, 0.6409, 0.8057],
        [1.6350, 0.9529, 1.6846],
        [0.6057, 1.3276, 0.4223],
        [0.8070, 0.8118, 1.0699],
        [1.1361, 1.3730, 1.0434]], dtype=torch.float64)

In [41]:
x+y

tensor([[0.2587, 0.6409, 0.8057],
        [1.6350, 0.9529, 1.6846],
        [0.6057, 1.3276, 0.4223],
        [0.8070, 0.8118, 1.0699],
        [1.1361, 1.3730, 1.0434]], dtype=torch.float64)

In [42]:
x.add_(y)

tensor([[0.2587, 0.6409, 0.8057],
        [1.6350, 0.9529, 1.6846],
        [0.6057, 1.3276, 0.4223],
        [0.8070, 0.8118, 1.0699],
        [1.1361, 1.3730, 1.0434]], dtype=torch.float64)

In [62]:
x = torch.randn(4, 4)

In [63]:
y = x.view(16) # 改变shape

In [65]:
z = x.view(-1, 8) # -1表示自动适配，后面为8前面就为2，后面为16前面就为1

x.size(), y.size(), z.size()

### numpy和tensor互转之后共用内存，如果当前变量在cpu中的话，一个改变会影响到另外一个

In [68]:
x = x.numpy()

In [69]:
x

array([[ 0.3603162 ,  0.23988713, -0.32799885, -1.0818669 ],
       [ 0.2596599 , -0.977443  , -0.5395732 ,  0.3756352 ],
       [-0.9836413 ,  1.9351236 ,  1.73508   , -1.7640477 ],
       [ 1.1834983 ,  0.9918474 ,  0.46588776, -0.5306321 ]],
      dtype=float32)

In [52]:
import numpy as np

In [72]:
x = np.ones(5)

In [73]:
x

array([1., 1., 1., 1., 1.])

In [74]:
y = torch.from_numpy(x)

In [75]:
y

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [76]:
y.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [77]:
x

array([2., 2., 2., 2., 2.])

### requires_grad 参数，如果该参数设为true，那么将会全程跟踪该函数的计算

In [128]:
x = torch.ones(2, 2, requires_grad=True) # out为scalar

In [129]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [130]:
y = x + 2

In [131]:
y.grad_fn

In [132]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [133]:
z = y * y * 3
out = z.mean()

In [134]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [135]:
out.backward() # 使用 backward 自动计算 gradient 并且存到 grad 属性中。

In [136]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [122]:
x = torch.randn(3, requires_grad=True)  # out不是scalar

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

In [123]:
y

tensor([475.9642, -24.6528, 896.8449], grad_fn=<MulBackward0>)

In [124]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)

In [125]:
y.backward(v)

In [126]:
x.grad

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])