In [2]:
import numpy as np

# 创建数组的简单使用

zeros

In [3]:
a = np.zeros((2, 3)) # 创建初始值为0的数组

In [4]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

ones

In [5]:
a = np.ones((2, 3)) # 创建初始值为1的数组

In [6]:
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

full

In [7]:
a = np.full((2, 3), 1) # 自定义初始值数组

In [8]:
a

array([[1, 1, 1],
       [1, 1, 1]])

array

In [9]:
a = np.array([1, 2, 3]) # 直接定义数组

In [10]:
a

array([1, 2, 3])

In [11]:
type(a) # 查看类型

numpy.ndarray

shape reshape()

In [12]:
a.shape # 存储数组维度的属性

(3,)

In [17]:
a = a.reshape((1, -1)) # 修改数组维度  -1代表占位符， numpy会自动根据数组维度填充

In [18]:
a.shape

(1, 3)

In [19]:
a = np.array([[1, 2, 3],
             [2, 3, 4]])

In [20]:
a.shape

(2, 3)

In [21]:
a = a.reshape((1, -1))

In [22]:
a

array([[1, 2, 3, 2, 3, 4]])

In [25]:
a = a.reshape((3, -1))

In [26]:
a

array([[1, 2],
       [3, 2],
       [3, 4]])

eye

In [28]:
a = np.eye(3) # 建立一个单位矩阵

In [29]:
a

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

random.random

In [30]:
a = np.random.random((3, 4)) # 创建0到1随机数的数组

In [31]:
a

array([[ 0.69618357,  0.18142677,  0.39221575,  0.75385024],
       [ 0.11044473,  0.11558231,  0.43917542,  0.68667204],
       [ 0.24562308,  0.46401773,  0.83062539,  0.77374122]])

# 索引操作

In [32]:
a = np.array([[1, 2, 3],
             [2, 3, 5],
             [3, 5, 1]])

In [33]:
a[1:, 1:3] # 1： 代表第一行之后， 1:3 代表第一列到第二列

array([[3, 5],
       [5, 1]])

arange

In [35]:
a = np.arange(3, 5) # 生成 【3， 5） 范围内的数

In [36]:
a

array([3, 4])

In [37]:
a[a > 3] # 查找大于3的数

array([4])

# 元素的数据类型

In [39]:
a = np.array([1, 2, 3]) # python会根据数值自动判断类型

In [40]:
a.dtype

dtype('int64')

In [41]:
a = np.array([22.2, 213])

In [42]:
a.dtype

dtype('float64')

In [43]:
a = np.array([22.2, 213], dtype=np.int64) # 强制定义类型

In [44]:
a

array([ 22, 213])

# 数组运算与常用函数

In [49]:
a = np.array([[1, 2],
          [2, 3]])

In [52]:
b = np.array([[2, 3],
            [2, 2]])

In [53]:
a+b

array([[3, 5],
       [4, 5]])

In [54]:
a-b

array([[-1, -1],
       [ 0,  1]])

In [55]:
a*b

array([[2, 6],
       [4, 6]])

In [56]:
a/b

array([[0, 0],
       [1, 1]])

In [57]:
np.sqrt(a) # 加根号

array([[ 1.        ,  1.41421356],
       [ 1.41421356,  1.73205081]])

In [58]:
a.dot(b) # 矩阵乘法

array([[ 6,  7],
       [10, 12]])

In [59]:
np.sum(a) # 计算总数

8

In [60]:
np.sum(a, axis=0) # 按照列计算总数

array([3, 5])

In [61]:
np.sum(a, axis=1) # 按照行计算总数

array([3, 5])

In [62]:
np.mean(a) # 求平均值， 和sum一样， 可以根据行或者列求值

2.0

uniform

In [63]:
np.random.uniform(2, 5) # 生成2到5之前的一个随机数

3.129391942119641

tile

In [65]:
a = np.array([[1, 2],
          [2, 3]])

In [66]:
np.tile(a, (1, 2)) # （1， 2）表示 行不变， 列按照原来的列横向扩充两列

array([[1, 2, 1, 2],
       [2, 3, 2, 3]])

argsort

In [67]:
a = np.array([[1, 2],
          [2, 3]])

In [68]:
np.argsort(a) # 返回排序之后数组元素的下标， 和sum一样， 可以根据行或者列排序 a.argsort(axis=0)

array([[0, 1],
       [0, 1]])

# 矩阵转置

In [73]:
a = np.array([[1, 1],
          [2, 6]])

In [74]:
a.T # 或者使用 np.transpose(a)

array([[1, 2],
       [1, 6]])

# 广播， 用处大

In [75]:
a = np.array([[1, 1],
          [2, 6]])

In [76]:
b = np.array([1, 1])

In [77]:
a+b # 数组维度不同相加，b会自动扩充至和a维度一样 

array([[2, 2],
       [3, 7]])